language: rust

cache:
  - cargo

rust:
  - 1.32.0
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
    - libasound2-dev
    - libsdl2-dev

install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      && brew install sdl2;
    fi

script:
  - cargo test --verbose
