[package]
name = "tetra"
description = "A simple 2D game framework written in Rust"
version = "0.2.14"
edition = "2018"
authors = ["Joe Clay <27cupsofcoffee@gmail.com>"]
license = "MIT"
repository = "https://github.com/17cupsofcoffee/tetra"
documentation = "https://docs.rs/tetra"
readme = "README.md"
keywords = ["game", "engine", "framework", "gamedev"]
categories = ["game-engines"]

[features]
sdl2_bundled = ["sdl2/bundled"]
sdl2_static_link = ["sdl2/static-link"]

[dependencies]
gl = "0.11.0"
sdl2 = "0.32.1"
image = "0.21.0"
glm = { version = "0.2.0", package = "nalgebra-glm" }
hashbrown = "0.1.8"
glyph_brush = "0.2.4"
rodio = "0.8.1"

[dev-dependencies]
rand = "0.6"
rand_core = "0.2.2" # workaround, see https://github.com/rust-random/rand/issues/645
